//
//  PDFExporter.swift
//  OPS
//
//  Single-page A4 PDF generator for a dimensioned photo (spec §3.7 office-
//  handoff PDF). Layout:
//
//    ┌────────────────────────────────────────────────────────────┐
//    │ // MEASURE                              ±5 MM · CALIBRATED │  ← header
//    │ PROJECT · 1042 ALDER ST · 2026-05-11 · CAPTURED BY J. SWEET │
//    ├────────────────────────────────────────────────────────────┤
//    │                                                            │
//    │                     [ rendered photo ]                     │  ← upper 55% of page
//    │                                                            │
//    ├────────────────────────────────────────────────────────────┤
//    │ DIMENSIONS                                                 │
//    │  WIDTH         36″     0.91 M                              │  ← table
//    │  HEIGHT        60″     1.52 M                              │
//    │  SILL HEIGHT   28″     0.71 M                              │
//    │  OPENING DEPTH  6″     0.15 M                              │
//    ├────────────────────────────────────────────────────────────┤
//    │ GENERATED BY OPS                              [logo mark]  │  ← footer
//    └────────────────────────────────────────────────────────────┘
//
//  Pure Core Graphics + PDFKit; no SwiftUI, no UIView — runs equally well
//  from a unit-test host (which is why `PDFExporterTests` can validate the
//  generated bytes without instantiating a view).
//
//  Spec reference:
//    ops-software-bible/specs/2026-05-10-lidar-dimensioned-photo-capture-design.md §3.7
//

import Foundation
import CoreGraphics
import UIKit
import PDFKit

public enum PDFExporter {

    public struct Metadata: Equatable {
        public let projectName: String
        public let address: String?
        public let capturedAt: Date
        public let capturedByName: String?

        public init(projectName: String,
                    address: String? = nil,
                    capturedAt: Date,
                    capturedByName: String? = nil) {
            self.projectName = projectName
            self.address = address
            self.capturedAt = capturedAt
            self.capturedByName = capturedByName
        }
    }

    public struct AccuracyDisplay: Equatable {
        public let text: String       // e.g. "±5 MM · CALIBRATED"
        public let coplanarOnly: Bool
        public init(text: String, coplanarOnly: Bool) {
            self.text = text
            self.coplanarOnly = coplanarOnly
        }
    }

    /// A4 portrait: 595 × 842 pt (PDF user-space, 72 dpi).
    public static let pageSize = CGSize(width: 595, height: 842)

    /// Render to PDF data. Returns `nil` if `photo` is nil and there is nothing
    /// to draw — callers should ensure photo is non-nil to avoid this path.
    public static func render(
        photo: UIImage?,
        dimensions: DimensionsData,
        metadata: Metadata,
        accuracy: AccuracyDisplay
    ) -> Data {
        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(origin: .zero, size: pageSize))
        return renderer.pdfData { ctx in
            ctx.beginPage()
            drawHeader(metadata: metadata, accuracy: accuracy)
            drawPhoto(photo)
            drawDimensionsTable(dimensions.measurements)
            drawFooter()
        }
    }

    // MARK: - Header

    private static let pagePadding: CGFloat = 28
    private static let headerHeight: CGFloat = 76
    private static let footerHeight: CGFloat = 36

    static func drawHeader(metadata: Metadata, accuracy: AccuracyDisplay) {
        let titleRect = CGRect(
            x: pagePadding,
            y: pagePadding,
            width: pageSize.width - pagePadding * 2,
            height: 22
        )
        attributedString("// MEASURE",
                         font: cakeMonoLight(16),
                         color: .black)
            .draw(at: titleRect.origin)

        // Accuracy chip — right aligned to first row.
        let chipText = accuracy.text + (accuracy.coplanarOnly ? "  COPLANAR ONLY" : "")
        let chipStr = attributedString(chipText, font: jbMono(10), color: .black)
        let chipSize = chipStr.size()
        chipStr.draw(at: CGPoint(
            x: pageSize.width - pagePadding - chipSize.width,
            y: pagePadding + 4
        ))

        // Metadata row.
        let metaParts: [String] = [
            metadata.projectName.uppercased(),
            metadata.address?.uppercased() ?? "",
            DateFormatter.opsLong.string(from: metadata.capturedAt),
            metadata.capturedByName.map { "CAPTURED BY \($0.uppercased())" } ?? ""
        ].filter { !$0.isEmpty }
        let metaLine = metaParts.joined(separator: " · ")
        attributedString(metaLine, font: jbMono(9), color: UIColor(white: 0.35, alpha: 1))
            .draw(at: CGPoint(x: pagePadding, y: pagePadding + 26))

        // Hairline under header.
        let line = UIBezierPath()
        line.move(to: CGPoint(x: pagePadding, y: pagePadding + headerHeight - 8))
        line.addLine(to: CGPoint(x: pageSize.width - pagePadding,
                                  y: pagePadding + headerHeight - 8))
        line.lineWidth = 0.5
        UIColor(white: 0.7, alpha: 1).setStroke()
        line.stroke()
    }

    // MARK: - Photo

    static func drawPhoto(_ photo: UIImage?) {
        let photoTop = pagePadding + headerHeight
        let photoMaxHeight = pageSize.height * 0.45
        let photoArea = CGRect(
            x: pagePadding,
            y: photoTop,
            width: pageSize.width - pagePadding * 2,
            height: photoMaxHeight
        )
        if let photo {
            let rect = aspectFit(photoArea: photoArea, imageSize: photo.size)
            photo.draw(in: rect)
        } else {
            // Empty-state outline so the page doesn't look broken in tests.
            UIColor(white: 0.85, alpha: 1).setStroke()
            UIBezierPath(rect: photoArea).stroke()
            attributedString("\u{2014}",
                             font: cakeMonoLight(28),
                             color: UIColor(white: 0.7, alpha: 1))
                .draw(at: CGPoint(
                    x: photoArea.midX - 8,
                    y: photoArea.midY - 18
                ))
        }
    }

    static func aspectFit(photoArea: CGRect, imageSize: CGSize) -> CGRect {
        guard imageSize.width > 0, imageSize.height > 0 else { return photoArea }
        let scale = min(photoArea.width / imageSize.width,
                        photoArea.height / imageSize.height)
        let size = CGSize(width: imageSize.width * scale,
                          height: imageSize.height * scale)
        return CGRect(
            x: photoArea.midX - size.width / 2,
            y: photoArea.midY - size.height / 2,
            width: size.width,
            height: size.height
        )
    }

    // MARK: - Dimensions table

    static func drawDimensionsTable(_ measurements: [DimensionsData.Measurement]) {
        let tableTop = pagePadding + headerHeight + pageSize.height * 0.45 + 18
        attributedString("DIMENSIONS",
                         font: cakeMonoLight(13),
                         color: .black,
                         tracking: 1)
            .draw(at: CGPoint(x: pagePadding, y: tableTop))

        var y = tableTop + 24
        let rowHeight: CGFloat = 22
        let labelX: CGFloat = pagePadding + 4
        let primaryX: CGFloat = pagePadding + 220
        let secondaryX: CGFloat = pagePadding + 340

        if measurements.isEmpty {
            attributedString("\u{2014}",
                             font: jbMono(11),
                             color: UIColor(white: 0.55, alpha: 1))
                .draw(at: CGPoint(x: labelX, y: y))
            return
        }

        for m in measurements {
            attributedString(m.label.uppercased(),
                             font: jbMono(11),
                             color: .black)
                .draw(at: CGPoint(x: labelX, y: y))

            let f = DimensionFormatter.format(
                valueMeters: m.valueMeters,
                primaryUnit: m.primaryDisplayUnit
            )
            attributedString(f.primary, font: jbMono(11), color: .black)
                .draw(at: CGPoint(x: primaryX, y: y))
            attributedString(f.secondary,
                             font: jbMono(11),
                             color: UIColor(white: 0.45, alpha: 1))
                .draw(at: CGPoint(x: secondaryX, y: y))

            y += rowHeight
        }
    }

    // MARK: - Footer

    static func drawFooter() {
        let footerY = pageSize.height - pagePadding - 16
        attributedString("GENERATED BY OPS",
                         font: cakeMonoLight(10),
                         color: UIColor(white: 0.45, alpha: 1),
                         tracking: 1)
            .draw(at: CGPoint(x: pagePadding, y: footerY))
    }

    // MARK: - Attributed string helper

    private static func attributedString(
        _ text: String,
        font: UIFont,
        color: UIColor,
        tracking: CGFloat = 0
    ) -> NSAttributedString {
        var attrs: [NSAttributedString.Key: Any] = [
            .font: font,
            .foregroundColor: color
        ]
        if tracking != 0 { attrs[.kern] = tracking }
        return NSAttributedString(string: text, attributes: attrs)
    }

    // MARK: - Fonts

    /// Falls back to system fonts when the OPS bundled families aren't loaded —
    /// keeps PDF generation working in unit-test hosts that don't register
    /// `CakeMono-Light` etc. The visual output in production uses the real
    /// families because they ARE registered by the app target at launch.
    private static func cakeMonoLight(_ size: CGFloat) -> UIFont {
        UIFont(name: "CakeMono-Light", size: size)
            ?? UIFont.systemFont(ofSize: size, weight: .light)
    }

    private static func jbMono(_ size: CGFloat) -> UIFont {
        UIFont(name: "JetBrainsMono-Regular", size: size)
            ?? UIFont.monospacedSystemFont(ofSize: size, weight: .regular)
    }
}

// MARK: - Date formatter

private extension DateFormatter {
    static let opsLong: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "yyyy-MM-dd"
        return f
    }()
}
