//
//  FollowUp.swift
//  OPS
//
//  Scheduled reminder — Supabase-backed.
//  Schema parity with public.follow_ups. `title` is REQUIRED (NOT NULL on DB,
//  no backfill trigger — iOS must always send it).
//

import SwiftData
import Foundation

@Model
class FollowUp: Identifiable {
    @Attribute(.unique) var id: String
    var companyId: String
    var opportunityId: String?       // nullable — follow-ups can attach to client without opportunity
    var clientId: String?
    var title: String                // REQUIRED — NOT NULL on DB, no trigger fallback
    var descriptionText: String?     // DB column: `description`
    var type: FollowUpType
    var status: FollowUpStatus
    var dueAt: Date
    var reminderAt: Date?
    var assignedTo: String?
    var createdBy: String?
    var completedAt: Date?
    var completionNotes: String?
    var isAutoGenerated: Bool
    var triggerSource: String?
    var createdAt: Date

    var isOverdue: Bool {
        status == .pending && dueAt < Date()
    }

    var isDueToday: Bool {
        status == .pending && Calendar.current.isDateInToday(dueAt)
    }

    init(
        id: String = UUID().uuidString,
        companyId: String,
        opportunityId: String?,
        title: String,
        type: FollowUpType,
        dueAt: Date,
        createdAt: Date = Date()
    ) {
        self.id = id
        self.companyId = companyId
        self.opportunityId = opportunityId
        self.title = title
        self.type = type
        self.status = .pending
        self.dueAt = dueAt
        self.isAutoGenerated = false
        self.createdAt = createdAt
    }
}
