//
//  FollowUpsCard.swift
//  OPS
//
//  Single-card surface on LeadDetailView showing the next unfinished
//  follow-up for this opportunity. Renders only when there is one —
//  consumers should check before composing into the parent stack.
//
//  Layout (L1 glass card):
//
//      // NEXT FOLLOW-UP
//      ● 2D OVERDUE                                     AUTO
//      Chase quote response
//
//  Tone derivation:
//    - dueAt < now (status pending) → rose  (overdue)
//    - dueAt is today               → tan   (due today)
//    - dueAt > now                  → neutral (text2)
//
//  AUTO indicator renders only when `isAutoGenerated` is true.
//

import SwiftUI

struct FollowUpsCard: View {
    let followUp: FollowUp

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            PanelSectionHeader(label: "NEXT FOLLOW-UP")
                .padding(.horizontal, 20)
                .padding(.bottom, 10)

            VStack(alignment: .leading, spacing: 8) {
                statusRow
                Text(followUp.title)
                    .font(.custom("Mohave-Medium", size: 14.5))
                    .foregroundColor(OPSStyle.Colors.text)
                    .multilineTextAlignment(.leading)
                    .lineLimit(2)
                    .fixedSize(horizontal: false, vertical: true)
            }
            .padding(.horizontal, 16)
            .padding(.vertical, 14)
            .frame(maxWidth: .infinity, alignment: .leading)
            .glassSurface()
            .padding(.horizontal, 20)
        }
    }

    // MARK: - Status row

    private var statusRow: some View {
        HStack(spacing: 10) {
            Circle()
                .fill(toneColor)
                .frame(width: 5, height: 5)

            Text(dueChipText)
                .font(.custom("JetBrainsMono-Regular", size: 10))
                .fontWeight(.semibold)
                .kerning(1.4)
                .foregroundColor(toneColor)
                .textCase(.uppercase)
                .monospacedDigit()

            Spacer(minLength: 8)

            if followUp.isAutoGenerated {
                Text("AUTO")
                    .font(.custom("JetBrainsMono-Regular", size: 9.5))
                    .kerning(1.3)
                    .foregroundColor(OPSStyle.Colors.textMute)
                    .textCase(.uppercase)
            }
        }
    }

    // MARK: - Derived

    /// Whole-day delta between today (midnight) and the follow-up's day.
    /// Negative = overdue, 0 = today, positive = future.
    private var dayDelta: Int {
        let cal = Calendar.current
        let from = cal.startOfDay(for: Date())
        let to = cal.startOfDay(for: followUp.dueAt)
        return cal.dateComponents([.day], from: from, to: to).day ?? 0
    }

    private var dueChipText: String {
        if dayDelta < 0  { return "\(-dayDelta)D OVERDUE" }
        if dayDelta == 0 { return "TODAY" }
        if dayDelta == 1 { return "TOMORROW" }
        return "IN \(dayDelta)D"
    }

    private var toneColor: Color {
        // Pending follow-ups can be overdue / due today / future.
        // Completed or skipped should render neutral since the action is past.
        guard followUp.status == .pending else {
            return OPSStyle.Colors.textMute
        }
        if dayDelta < 0  { return OPSStyle.Colors.roseTextM }
        if dayDelta == 0 { return OPSStyle.Colors.tanTextM }
        return OPSStyle.Colors.text2
    }
}

// MARK: - Previews

#if DEBUG
#Preview("FollowUpsCard / tones") {
    ScrollView {
        VStack(spacing: 22) {
            FollowUpsCard(followUp: {
                let f = FollowUp(
                    companyId: "preview",
                    opportunityId: "preview",
                    title: "Chase quote response",
                    type: .quoteFollowUp,
                    dueAt: Calendar.current.date(byAdding: .day, value: -2, to: Date())!
                )
                f.isAutoGenerated = true
                return f
            }())

            FollowUpsCard(followUp: FollowUp(
                companyId: "preview",
                opportunityId: "preview",
                title: "Close — sign + deposit",
                type: .call,
                dueAt: Date()
            ))

            FollowUpsCard(followUp: FollowUp(
                companyId: "preview",
                opportunityId: "preview",
                title: "Reach out — initial contact",
                type: .call,
                dueAt: Calendar.current.date(byAdding: .day, value: 3, to: Date())!
            ))

            FollowUpsCard(followUp: FollowUp(
                companyId: "preview",
                opportunityId: "preview",
                title: "Tomorrow — site walk re-check",
                type: .meeting,
                dueAt: Calendar.current.date(byAdding: .day, value: 1, to: Date())!
            ))
        }
        .padding(.vertical, 24)
    }
    .background(OPSStyle.Colors.background)
    .preferredColorScheme(.dark)
}
#endif
