-- Migration: add_calendar_event_series_id
-- Run in Supabase SQL editor for project: ijeekuhbatykdomumfjx.supabase.co
-- Created: 2026-04-30
-- Purpose: enable Apple-Calendar-style "edit one / edit future / edit all"
--          semantics for recurring personal events. Every row generated by
--          the recurrence expansion gets the same series_id; rows with
--          series_id IS NULL are detached singletons (or events created
--          before this migration shipped).

ALTER TABLE calendar_user_events
  ADD COLUMN IF NOT EXISTS series_id uuid;

-- Partial index — most rows are non-recurring, so we only index siblings
-- that actually belong to a series. Keeps the index small while still
-- making "fetch all rows where series_id = X" a single seek.
CREATE INDEX IF NOT EXISTS calendar_user_events_series_id_idx
  ON calendar_user_events (series_id) WHERE series_id IS NOT NULL;
