//
//  PDFExporterTests.swift
//  OPSTests
//
//  Spec reference:
//    ops-software-bible/specs/2026-05-10-lidar-dimensioned-photo-capture-design.md §3.7
//

import XCTest
import PDFKit
import UIKit
@testable import OPS

final class PDFExporterTests: XCTestCase {

    private func fixtureDimensions() -> DimensionsData {
        return DimensionsData(
            captureMode: .lidar,
            calibration: .init(method: .lidar, estimatedAccuracyMeters: 0.025),
            intrinsics: .init(fx: 1593.4, fy: 1593.4,
                              cx: 1015.5, cy: 762.0,
                              imageWidth: 4032, imageHeight: 3024),
            measurements: [
                .init(type: .linear,
                      label: "Width",
                      worldPoints: [.init(x: 0, y: 0, z: 0), .init(x: 0.9144, y: 0, z: 0)],
                      imagePoints: [.init(x: 100, y: 500), .init(x: 800, y: 500)],
                      valueMeters: 0.9144,
                      labelPlacement: .init(side: .north, leaderLengthPx: 60),
                      source: .auto),
                .init(type: .linear,
                      label: "Height",
                      worldPoints: [.init(x: 0, y: 0, z: 0), .init(x: 0, y: 1.524, z: 0)],
                      imagePoints: [.init(x: 100, y: 500), .init(x: 100, y: 1900)],
                      valueMeters: 1.524,
                      labelPlacement: .init(side: .east, leaderLengthPx: 60),
                      source: .auto)
            ],
            openings: []
        )
    }

    private func fixturePhoto() -> UIImage {
        let renderer = UIGraphicsImageRenderer(size: CGSize(width: 200, height: 200))
        return renderer.image { ctx in
            UIColor.darkGray.setFill()
            ctx.fill(CGRect(x: 0, y: 0, width: 200, height: 200))
            UIColor.white.setStroke()
            UIBezierPath(rect: CGRect(x: 40, y: 40, width: 120, height: 120)).stroke()
        }
    }

    func test_render_producesValidSinglePagePDF() {
        let data = PDFExporter.render(
            photo: fixturePhoto(),
            dimensions: fixtureDimensions(),
            metadata: .init(projectName: "1042 Alder St",
                            address: "Vancouver BC",
                            capturedAt: Date(timeIntervalSince1970: 1747166400),
                            capturedByName: "J. Sweet"),
            accuracy: .init(text: "±5 MM · CALIBRATED", coplanarOnly: false)
        )
        XCTAssertGreaterThan(data.count, 500, "PDF should be non-empty")
        let doc = PDFDocument(data: data)
        XCTAssertNotNil(doc, "Generated bytes must parse as a PDFDocument")
        XCTAssertEqual(doc?.pageCount, 1, "Single-page PDF per spec §3.7")
    }

    func test_render_emptyMeasurements_stillProducesValidPDF() {
        var dims = fixtureDimensions()
        dims.measurements = []
        let data = PDFExporter.render(
            photo: fixturePhoto(),
            dimensions: dims,
            metadata: .init(projectName: "X",
                            capturedAt: Date(),
                            capturedByName: nil),
            accuracy: .init(text: "NO DEPTH · ESTIMATE", coplanarOnly: false)
        )
        let doc = PDFDocument(data: data)
        XCTAssertEqual(doc?.pageCount, 1)
    }

    func test_render_nilPhoto_drawsEmptyState() {
        let data = PDFExporter.render(
            photo: nil,
            dimensions: fixtureDimensions(),
            metadata: .init(projectName: "X",
                            capturedAt: Date(),
                            capturedByName: nil),
            accuracy: .init(text: "±1″ · LIDAR", coplanarOnly: false)
        )
        let doc = PDFDocument(data: data)
        XCTAssertNotNil(doc)
        XCTAssertEqual(doc?.pageCount, 1)
    }

    func test_pageSizeIsA4() {
        XCTAssertEqual(PDFExporter.pageSize.width, 595)
        XCTAssertEqual(PDFExporter.pageSize.height, 842)
    }

    func test_aspectFit_centresAndScalesProportionally() {
        let area = CGRect(x: 0, y: 0, width: 200, height: 100)
        let fit = PDFExporter.aspectFit(photoArea: area,
                                        imageSize: CGSize(width: 400, height: 100))
        XCTAssertEqual(fit.width, 200)
        XCTAssertEqual(fit.height, 50)
        XCTAssertEqual(fit.midX, area.midX, accuracy: 0.5)
        XCTAssertEqual(fit.midY, area.midY, accuracy: 0.5)
    }
}
